[package]
name = "erars-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
lalrpop-util = "0.19.7"
memchr = "2.4.1"
serde = { version = "1.0.136", features = ["derive"] }
source-span = { version = "2.7.0", default-features = false }
thiserror = "1.0.30"
utf8-decode = "1.0.1"

[build-dependencies]
lalrpop = "0.19.7"

[dev-dependencies]
k9 = "0.11.1"
