[package]
name = "erars-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
either = { version = "1.6.1", features = ["serde"] }
enum-map = { version = "2.0.3", features = ["serde"] }
hashbrown = { version = "0.12.0", features = ["serde"] }
memchr = "2.4.1"
option_set = "0.1.4"
serde = { version = "1.0.136", features = ["derive"] }
strum = { version = "0.24.0", features = ["derive"] }
thiserror = "1.0.30"
utf8-decode = "1.0.1"

[dev-dependencies]
k9 = "0.11.1"
