[package]
name = "erars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
anyhow = "1.0.52"
bitflags = "1.3.2"
itertools = "0.10.3"
once_cell = "1.9.0"
pest = { version = "2.1.3", features = ["pretty-print"] }
pest_derive = "2.1.0"
# wgpu = "0.12.0"
# wgpu_glyph = "0.16.0"
# winit = "0.26.0"

[dev-dependencies]
criterion = "0.3.5"
k9 = "0.11.1"

[[bench]]
name = "parse"
harness = false
