[package]
name = "erars"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./erars-compiler",
    "./erars-lexer",
    "./erars-ast",
]

[dependencies]
erars-ast = { path = "./erars-ast" }
erars-compiler = { path = "./erars-compiler" }
anyhow = "1.0.52"
arrayvec = { version = "0.7.2", features = ["serde"] }
bitflags = "1.3.2"
crossbeam-channel = "0.5.2"
enum-map = { version = "2.0.0", features = ["serde"] }
glob = "0.3.0"
hashbrown = { version = "0.12", features = ["serde", "rayon"] }
itertools = "0.10.3"
log = "0.4.14"
serde = { version = "1.0.132", features = ["derive"] }
serde_yaml = "0.8.23"
strum = { version = "0.23.0", features = ["derive"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
smol_str = { version = "0.1.23", features = ["serde"] }
rayon = "1.5.3"
parking_lot = "0.12.1"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
ansi_term = { version = "0.12.1", optional = true }
unicode-width = "0.1.9"
encoding_rs = "0.8.31"
pad = "0.1.6"
clap = { version = "3.2.17", features = ["suggestions", "derive"] }
ron = "0.7.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
flexi_logger = "0.23.3"

[dev-dependencies]
criterion = "0.3.5"
k9 = "0.11.1"
glob = "0.3.0"

[[bench]]
name = "parse"
harness = false

[features]
default = ["stdio-backend"]
stdio-backend = ["ansi_term"]
