[package]
name = "erars"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./erars-compiler",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erars-compiler = { path = "./erars-compiler" }
anyhow = "1.0.52"
arrayvec = { version = "0.7.2", features = ["serde"] }
bitflags = "1.3.2"
crossbeam-channel = "0.5.2"
eframe = "0.17"
egui = "0.17"
either = "1.6.1"
enum-map = { version = "2.0.0", features = ["serde"] }
glob = "0.3.0"
hashbrown = { version = "0.12", features = ["serde"] }
itertools = "0.10.3"
log = "0.4.14"
maplit = "1.0.2"
once_cell = "1.9.0"
pest = { version = "2.1.3", features = ["pretty-print"] }
pest_derive = "2.1.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_yaml = "0.8.23"
strum = { version = "0.23.0", features = ["derive"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
smartstring = { version = "1.0.1", features = ["serde"] }

[dev-dependencies]
criterion = "0.3.5"
k9 = "0.11.1"
glob = "0.3.0"
ron = "0.7.0"

[[bench]]
name = "parse"
harness = false

[features]
