[package]
name = "erars-saveload-web"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
erars-vm = { path = "../erars-vm" }
serde_json = "1.0.86"
web-sys = { version = "0.3.60", features = ["Storage", "Window"] }
