[package]
name = "erars-bytecode"
version = "0.4.0"
edition = "2021"

[dependencies]
erars-ast = { path = "../erars-ast" }
erars-vm = { path = "../erars-vm" }

byteorder = "1.4.3"
enum-map = "2.4.1"
hashbrown = "0.13.1"
