name: Nightly

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cargo Target Cache
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release
          ${{ runner.os }}-cargo-target-release
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars
        path: target/release/erars

  release-win:
    runs-on: windows-latest
    
    steps:
    - name: Cargo Target Cache
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release
          ${{ runner.os }}-cargo-target-release
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars.exe
        path: target/release/erars.exe
