name: Nightly

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-win:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release-lto
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release-lto
          ${{ runner.os }}-cargo-target-release-lto
    - name: Build
      run: |
        cargo build --profile=release-lto -p erars-stdio -p erars-egui --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars-stdio.exe
        path: target/release-lto/erars-stdio.exe
    - uses: actions/upload-artifact@v3
      with:
        name: erars-egui.exe
        path: target/release-lto/erars-egui.exe
        
  release-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release-lto
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release-lto
          ${{ runner.os }}-cargo-target-release-lto
    - name: Build
      run: |
        cargo build --profile=release-lto -p erars-stdio -p erars-egui --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars-stdio
        path: target/release-lto/erars-stdio
    - uses: actions/upload-artifact@v3
      with:
        name: erars-egui
        path: target/release-lto/erars-egui
