name: Nightly

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Cargo Target Cache
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release
          ${{ runner.os }}-cargo-target-release
    - name: Build
      run: |
        cargo build --release -p erars-stdio -p erars-http --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars-stdio
        path: target/release/erars_stdio
    - uses: actions/upload-artifact@v3
      with:
        name: erars-http
        path: target/release/erars_http

  release-win:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Cargo Target Cache
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}-release
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.toml') }}-release
          ${{ runner.os }}-cargo-target-release
    - name: Build
      run: |
        cargo build --release -p erars-stdio -p erars-http --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: erars-stdio.exe
        path: target/release/erars-stdio.exe
    - uses: actions/upload-artifact@v3
      with:
        name: erars-http.exe
        path: target/release/erars-http.exe
